import React, { useState } from "react";
import Head from "next/head";
import Tiptap from "../components/Tiptap";
import ScrollToBottom from "react-scroll-to-bottom";
import { css } from "@emotion/react";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";

export default function Home() {
	const [sidebar, setSidebar] = useState(true);
	const ROOT_CSS = css({
		height: 500,
		width: 400,
	});
	return (
		<div>
			<Head>
				<title>Thread Builder</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<section>
				<Header sidebar={sidebar} setSidebar={setSidebar} />
				<main className="flex">
					<div
						className={`py-2 px-4 hidden lg:block ${sidebar ? "w-72" : "w-0"} `}
					>
						<Sidebar />
					</div>
					<div className="w-full md:w-6/12 lg:w-5/12 mx-auto mt-4 p-2">
						<ScrollToBottom className={ROOT_CSS}>
							<Tiptap />
						</ScrollToBottom>
					</div>
				</main>
			</section>
		</div>
	);
}
