import Head from 'next/head'
import Tiptap from '../components/Tiptap'
import ScrollToBottom from 'react-scroll-to-bottom'
import { css } from '@emotion/react'
import ActionBar from '../components/ActionBar'
import Header from '../components/Header'

export default function Home() {
  const ROOT_CSS = css({
    height: 500,
    width: 400
  })
  return (
    <div>
      <Head>
        <title>Thread Builder</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section className='h-screen'>
        <Header />
        <div className='container w-full md:w-7/12 lg:w-4/12 mx-auto px-2 py-4'>
          <ScrollToBottom className={ROOT_CSS}>
            <Tiptap />
          </ScrollToBottom>
        </div>
      </section>
    </div>
  )
}
