import Head from 'next/head'
import Tiptap from '../components/Tiptap'
import ScrollToBottom from 'react-scroll-to-bottom'
import { css } from '@emotion/react'

export default function Home() {
  const ROOT_CSS = css({
    height: 500,
    width: 400
  })
  return (
    <div>
      <Head>
        <title>Thread Builder</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='container w-full md:w-6/12 lg:w-4/12 mx-auto p-3'>
        <ScrollToBottom className={ROOT_CSS}>
          <Tiptap />
        </ScrollToBottom>
      </div>
    </div>
  )
}
