import Head from "next/head";
import Tiptap from "../components/Tiptap";

export default function Home() {
	const sidebar = true;
	return (
		<div>
			<Head>
				<title>Thread Builder</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<section>
				<main className="flex">
					<div
						className={`py-2 px-4 hidden lg:block ${sidebar ? "w-72" : "w-0"} `}
					/>
					<div className="w-full md:w-6/12 lg:w-5/12 mx-auto mt-4 p-2">
						<Tiptap />
					</div>
				</main>
			</section>
		</div>
	);
}
